### ISSUE TITLE
输入ticket后报错

### ISSUE THREAD

**Issue by JohnnieWind** [kosaka-bun/jar-launcher#4]
<img width="1548" alt="image" src="https://github.com/kosaka-bun/qqrobot-sdk/assets/34503500/61b49a46-f74c-49aa-a76b-5025b3dcb505">

**Comment by JohnnieWind** [comment]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.StackOverflowError
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:708)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66)
        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
        at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)

**Comment by kosaka-bun** [comment]
这是mirai的一个常见问题，往往就发生在这种情况下。
推测可能与设备锁等因素有关，建议先关闭账号的登录保护与设备锁之后再试。
